"""empty message

Revision ID: 14966dfebac4
Revises: 
Create Date: 2018-05-18 22:21:38.684803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14966dfebac4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form')
    # ### end Alembic commands ###
