"""empty message

Revision ID: e4834c5cf698
Revises: 14966dfebac4
Create Date: 2018-05-18 23:16:04.952706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4834c5cf698'
down_revision = '14966dfebac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('a_type', sa.String(length=80), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('form', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.drop_table('field')
    # ### end Alembic commands ###
